import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import product from '../products.json';

export default function Home() {
 
  return (
    <div className={styles.container}>
      <Head>
        <title>My Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        MY SHOP
        </h1>

        <p className={styles.description}>
         
         
        </p>
        <div className={styles.grid}>
              
          {product.map(item => {
        return( 
            <a key={item.price}  className={styles.card}>
            <h2 >{item.title}</h2>
            <Image src={item.image} alt="shoes" width={300} height={200} />
            <p>{item.description}</p>
            <h2>${item.price}</h2>
            <button>Buy</button>
          </a>     )     
        
    })}

    </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
